<?php

namespace Diflowrin\ContentGenerator\Services;

use WP_Error;

defined( 'ABSPATH' ) || exit;

/**
 * The single gate between a remote image and this site's uploads folder.
 *
 * Every image the plugin stores — generated by a model or downloaded from a
 * stock library — passes through here, so the rules about what may be written
 * to disk live in exactly one place.
 */
class RemoteImage {

	/**
	 * Image types we accept, and the extension each is stored under. Anything
	 * else is refused rather than written to the uploads folder.
	 *
	 * @var array<string,string>
	 */
	const TYPES = array(
		'image/png'  => 'png',
		'image/jpeg' => 'jpg',
		'image/webp' => 'webp',
		'image/gif'  => 'gif',
	);

	/**
	 * File extension for a MIME type, defaulting to png for unknown ones.
	 *
	 * @param string $mime MIME type.
	 * @return string
	 */
	public static function extension( $mime ) {
		return isset( self::TYPES[ $mime ] ) ? self::TYPES[ $mime ] : 'png';
	}

	/**
	 * Download an image over HTTP.
	 *
	 * @param string $url     Image URL (from an API response — not trusted).
	 * @param int    $timeout Seconds.
	 * @return array{bytes:string,mime:string}|WP_Error
	 */
	public static function fetch( $url, $timeout = 60 ) {
		$response = wp_remote_get(
			$url,
			array(
				'timeout' => $timeout,
				// The URL comes from a third-party response, so it is not blindly
				// trusted: this keeps it from being pointed at an internal host.
				'reject_unsafe_urls' => true,
			)
		);
		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = (int) wp_remote_retrieve_response_code( $response );
		if ( $code < 200 || $code >= 300 ) {
			return new WP_Error(
				'diflowrin_content_generator_image_fetch',
				sprintf(
					/* translators: %d: HTTP status code. */
					__( 'The image could not be downloaded (HTTP %d).', 'diflowrin-ai-content-generation' ),
					$code
				)
			);
		}

		$mime = strtolower( (string) wp_remote_retrieve_header( $response, 'content-type' ) );
		$mime = trim( explode( ';', $mime )[0] );

		return self::validate( wp_remote_retrieve_body( $response ), $mime );
	}

	/**
	 * Decode a base64 data URI.
	 *
	 * @param string $source Data URI.
	 * @return array{bytes:string,mime:string}|WP_Error
	 */
	public static function from_data_uri( $source ) {
		if ( ! preg_match( '#^data:([a-z0-9.+/-]+);base64,(.+)$#is', $source, $matches ) ) {
			return new WP_Error( 'diflowrin_content_generator_bad_image', __( 'The image data could not be read.', 'diflowrin-ai-content-generation' ) );
		}

		$bytes = base64_decode( $matches[2], true ); // phpcs:ignore WordPress.PHP.DiscouragedPHPFunctions.obfuscation_base64_decode -- decoding an inline image payload, not obfuscation.
		if ( false === $bytes ) {
			return new WP_Error( 'diflowrin_content_generator_bad_image', __( 'The returned image could not be decoded.', 'diflowrin-ai-content-generation' ) );
		}

		return self::validate( $bytes, strtolower( $matches[1] ) );
	}

	/**
	 * Read whatever a provider handed back: an inline data URI or a URL.
	 *
	 * @param string $source Data URI or http(s) URL.
	 * @param int    $timeout Seconds, when a download is needed.
	 * @return array{bytes:string,mime:string}|WP_Error
	 */
	public static function read( $source, $timeout = 60 ) {
		return 0 === strpos( strtolower( (string) $source ), 'data:' )
			? self::from_data_uri( $source )
			: self::fetch( $source, $timeout );
	}

	/**
	 * Guard the uploads folder: only known image types, and only payloads that
	 * really are images.
	 *
	 * @param string $bytes Raw image data.
	 * @param string $mime  Declared MIME type.
	 * @return array{bytes:string,mime:string}|WP_Error
	 */
	public static function validate( $bytes, $mime ) {
		if ( '' === (string) $bytes ) {
			return new WP_Error( 'diflowrin_content_generator_empty_image', __( 'The image was empty.', 'diflowrin-ai-content-generation' ) );
		}
		if ( ! isset( self::TYPES[ $mime ] ) ) {
			return new WP_Error(
				'diflowrin_content_generator_image_type',
				sprintf(
					/* translators: %s: MIME type that was returned. */
					__( 'Unsupported image type (%s).', 'diflowrin-ai-content-generation' ),
					'' !== $mime ? $mime : __( 'unknown', 'diflowrin-ai-content-generation' )
				)
			);
		}
		// The declared type is only a claim; confirm the bytes are a real image.
		if ( function_exists( 'getimagesizefromstring' ) && false === @getimagesizefromstring( $bytes ) ) { // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged -- a malformed payload is reported below, not as a PHP warning.
			return new WP_Error( 'diflowrin_content_generator_bad_image', __( 'The file is not a readable image.', 'diflowrin-ai-content-generation' ) );
		}

		return array(
			'bytes' => $bytes,
			'mime'  => $mime,
		);
	}
}
